// 5 questions per module, 12 modules = 60 total
export const QUIZ_DATA = {
  ai: {
    1: {
      title: "AI Basics and Responsible Use",
      questions: [
        {
          q: "What is artificial intelligence?",
          opts: ["A robot with human emotions", "Computer systems that perform tasks normally requiring human intelligence", "A search engine that indexes websites", "A type of social media algorithm"],
          correct: 1,
          explanation: "AI refers to computer systems that perform tasks normally requiring human intelligence such as pattern recognition and language understanding."
        },
        {
          q: "What does 'hallucination' mean in the context of AI?",
          opts: ["AI daydreaming during idle time", "AI producing information that sounds real but is false or invented", "AI refusing to answer a question", "AI running out of memory"],
          correct: 1,
          explanation: "Hallucination is when AI generates content that sounds plausible but is factually wrong or made up."
        },
        {
          q: "Which of the following is an example of generative AI?",
          opts: ["A spam filter", "A navigation map", "ChatGPT writing an email draft", "A barcode scanner"],
          correct: 2,
          explanation: "Generative AI creates new content — text, images, audio — like ChatGPT generating email drafts."
        },
        {
          q: "What is responsible AI use?",
          opts: ["Letting AI make all decisions for you", "Using AI without checking its outputs", "Using AI safely, ethically, and with human judgement", "Only using AI tools made by trusted brands"],
          correct: 2,
          explanation: "Responsible AI use means applying human judgement, verifying outputs, and considering ethical implications."
        },
        {
          q: "Why is verification important when using AI outputs?",
          opts: ["AI is always correct so verification is unnecessary", "AI can produce inaccurate or hallucinated information", "Verification slows down productivity", "AI tools require a fee for accurate results"],
          correct: 1,
          explanation: "AI can hallucinate or produce outdated information, so checking outputs against reliable sources is essential."
        },
      ]
    },
    2: {
      title: "Prompting 101",
      questions: [
        {
          q: "What is a prompt in the context of AI tools?",
          opts: ["A software update notification", "The instruction, question, or request given to an AI tool", "A menu option in an AI app", "The AI's response"],
          correct: 1,
          explanation: "A prompt is the input you give to an AI — the instruction or question that guides its response."
        },
        {
          q: "Which of the following is a stronger prompt?",
          opts: ["Write an email", "Write a professional email to a client apologising for a delivery delay, in a friendly but formal tone, under 100 words", "Tell me something", "Help me with work"],
          correct: 1,
          explanation: "A strong prompt includes task, context, tone, and constraints — making it easier for AI to give a useful response."
        },
        {
          q: "What is a follow-up prompt?",
          opts: ["A second AI tool you use after the first", "An additional prompt used to refine or improve the AI's first response", "A prompt you send the next day", "A summary of what the AI wrote"],
          correct: 1,
          explanation: "Follow-up prompts help you iterate on AI outputs — asking it to adjust tone, add detail, or reformat."
        },
        {
          q: "What does 'tone' mean in a prompt?",
          opts: ["The volume of the AI's voice", "How the response should sound — formal, friendly, or professional", "The font size of the output", "The length of the response"],
          correct: 1,
          explanation: "Tone tells the AI how the writing should feel — such as friendly, formal, persuasive, or empathetic."
        },
        {
          q: "What should you do after receiving an AI output?",
          opts: ["Use it immediately without reading it", "Delete it if it is not perfect", "Review it for accuracy, tone, and appropriateness before using", "Always rewrite it completely from scratch"],
          correct: 2,
          explanation: "AI outputs should always be reviewed — checked for errors, adjusted for context, and verified before use."
        },
      ]
    },
    3: {
      title: "AI for Productivity and Communication",
      questions: [
        {
          q: "What is an AI-assisted draft?",
          opts: ["A document written entirely by AI with no human involvement", "A first version of content generated by AI that a human then reviews and edits", "A draft that AI rejects", "A prompt template"],
          correct: 1,
          explanation: "An AI-assisted draft is a starting point — AI generates it, and a human improves and validates it."
        },
        {
          q: "Which task is AI well-suited to help with at work?",
          opts: ["Signing legal documents on your behalf", "Summarising long reports into key points", "Making final decisions about hiring", "Replacing your manager"],
          correct: 1,
          explanation: "AI excels at summarisation, drafting, and structuring — saving time on repetitive communication tasks."
        },
        {
          q: "What is tone editing?",
          opts: ["Adjusting the volume of an AI voice assistant", "Changing the emotional register of writing — formal, friendly, urgent", "Removing grammar errors from a document", "Adding emojis to messages"],
          correct: 1,
          explanation: "Tone editing means adjusting how a piece of writing feels — its emotional register and formality level."
        },
        {
          q: "Why should you review AI-generated emails before sending?",
          opts: ["AI emails are too long", "AI may include incorrect facts, wrong tone, or details that don't apply to your situation", "Email clients don't support AI text", "AI always writes in another language"],
          correct: 1,
          explanation: "AI cannot know all the context of your relationship or situation — review ensures the message is accurate and appropriate."
        },
        {
          q: "What does 'summarisation' mean?",
          opts: ["Making a document longer and more detailed", "Condensing longer content into its key points without losing meaning", "Translating a document into another language", "Adding bullet points to a report"],
          correct: 1,
          explanation: "Summarisation distils the essential meaning of longer content — AI can do this quickly but accuracy should be checked."
        },
      ]
    },
    4: {
      title: "AI for Research, Content and Workflow",
      questions: [
        {
          q: "What is a 'knowledge cutoff' in AI?",
          opts: ["When an AI stops responding due to overload", "The date after which an AI model has no information about world events", "The maximum number of words an AI can read", "A filter that blocks certain topics"],
          correct: 1,
          explanation: "AI models are trained on data up to a certain date — after that cutoff, they have no knowledge of new events."
        },
        {
          q: "What is source verification?",
          opts: ["Checking your internet connection", "Confirming that a claim or statistic comes from a reliable, authoritative source", "Verifying your email address", "Scanning a document for viruses"],
          correct: 1,
          explanation: "Source verification means tracing AI-provided facts back to credible original sources before using them."
        },
        {
          q: "What is content repurposing?",
          opts: ["Deleting old content to make room for new content", "Taking existing content and adapting it for a different format or audience", "Copying someone else's content", "Translating content into images"],
          correct: 1,
          explanation: "Repurposing means transforming existing content — e.g. turning a blog post into social media captions or a presentation."
        },
        {
          q: "What is an AI workflow?",
          opts: ["A robot assembly line", "A defined sequence of steps that incorporates AI tools at specific points to improve efficiency", "A chat conversation with an AI", "A type of project management software"],
          correct: 1,
          explanation: "An AI workflow maps out where AI fits in your process — which tasks it handles and how outputs flow to the next step."
        },
        {
          q: "When using AI for research, you should always:",
          opts: ["Trust every fact AI provides without checking", "Never use AI for research", "Cross-check AI outputs with credible sources before citing them", "Only use AI to find images"],
          correct: 2,
          explanation: "AI can hallucinate citations and statistics — always verify research outputs against authoritative sources."
        },
      ]
    },
  },

  hygiene: {
    1: {
      title: "Digital Hygiene Basics",
      questions: [
        {
          q: "What is digital hygiene?",
          opts: ["Cleaning your phone screen regularly", "Practices that keep your digital life safe, clean, organised, and responsible", "Only using apps approved by your employer", "Logging out of every website after use"],
          correct: 1,
          explanation: "Digital hygiene is a broad set of habits — from strong passwords to careful sharing — that protect your digital life."
        },
        {
          q: "What is a digital footprint?",
          opts: ["A watermark on a digital photo", "The trail of data left behind when you use the internet or digital devices", "A type of virus that tracks your location", "Your saved browser bookmarks"],
          correct: 1,
          explanation: "Every click, post, and login leaves data behind — your digital footprint is the sum of all that activity."
        },
        {
          q: "Which of the following is personal data?",
          opts: ["A public company's trading hours", "Your IC number, phone number, or email address", "The weather forecast", "A dictionary definition"],
          correct: 1,
          explanation: "Personal data is any information that can identify you — IC number, email, location, biometrics, and more."
        },
        {
          q: "What is a privacy setting?",
          opts: ["A mode that makes your device run faster", "Controls that limit who can see your information or activity online", "A parental control feature", "A setting that deletes your history automatically"],
          correct: 1,
          explanation: "Privacy settings let you control who can see your posts, profile, and activity on apps and websites."
        },
        {
          q: "Why does digital hygiene matter in the workplace?",
          opts: ["It only matters for personal use at home", "Poor digital habits can lead to data breaches, embarrassment, or financial harm", "It only affects your internet speed", "Digital hygiene is optional for employees"],
          correct: 1,
          explanation: "Workplace data breaches, leaked files, and professional reputation damage often trace back to poor digital habits."
        },
      ]
    },
    2: {
      title: "Accounts, Passwords and Device Safety",
      questions: [
        {
          q: "What makes a strong password?",
          opts: ["Your name and birth year", "A mix of uppercase, lowercase, numbers, and symbols — at least 12 characters", "A common word that is easy to remember", "The same password you use for everything"],
          correct: 1,
          explanation: "Strong passwords are long, complex, and unique — a mix of character types that is hard to guess or crack."
        },
        {
          q: "What is multi-factor authentication (MFA)?",
          opts: ["Logging in from multiple devices at once", "A login method requiring two or more verification steps, such as a password plus an OTP", "Having multiple email accounts", "A type of antivirus software"],
          correct: 1,
          explanation: "MFA adds a second layer — even if your password is stolen, attackers cannot access your account without the second factor."
        },
        {
          q: "What is a password manager?",
          opts: ["A person who manages your accounts for you", "A tool that securely stores and autofills passwords so you don't need to remember them", "A notepad where you write down passwords", "A browser setting that blocks weak passwords"],
          correct: 1,
          explanation: "Password managers encrypt and store all your passwords — you only need to remember one master password."
        },
        {
          q: "Why should you keep your device software updated?",
          opts: ["Updates only add new features and are optional", "Updates patch security vulnerabilities that attackers could exploit", "Updates slow down your device intentionally", "Updates are only needed for old devices"],
          correct: 1,
          explanation: "Software updates fix known security flaws — delaying them leaves your device exposed to known attacks."
        },
        {
          q: "What is phishing?",
          opts: ["A legitimate marketing email", "A scam that tricks you into revealing login credentials or personal information", "A type of antivirus scan", "A method of resetting your password"],
          correct: 1,
          explanation: "Phishing uses deceptive messages — often impersonating banks or employers — to steal your credentials or money."
        },
      ]
    },
    3: {
      title: "Digital Organisation and Information Management",
      questions: [
        {
          q: "What is a file naming convention?",
          opts: ["A law about how files must be named", "A consistent system for naming files so they are easy to find and sort", "The file extension at the end of a filename", "A folder structure template"],
          correct: 1,
          explanation: "File naming conventions — like including date, project, and version — make files searchable and reduce confusion."
        },
        {
          q: "What is cloud storage?",
          opts: ["Storing files on a USB drive", "Online storage that lets you access files from any device connected to the internet", "A backup hard drive kept at a separate location", "A type of file compression"],
          correct: 1,
          explanation: "Cloud storage — like Google Drive or OneDrive — keeps your files online so you can access them from anywhere."
        },
        {
          q: "What is digital declutter?",
          opts: ["Removing physical clutter from your desk", "Removing unnecessary files, apps, and data to keep your digital environment organised", "Deleting your social media accounts", "Clearing your browser cache only"],
          correct: 1,
          explanation: "Digital declutter means regularly removing files, emails, and apps you no longer need to stay organised and secure."
        },
        {
          q: "What is email inbox hygiene?",
          opts: ["Using a spam filter only", "Organising, unsubscribing, and regularly clearing your inbox to keep communication manageable", "Checking email only once a day", "Deleting all emails immediately after reading"],
          correct: 1,
          explanation: "Inbox hygiene includes unsubscribing from junk, using folders, and regularly archiving or deleting old messages."
        },
        {
          q: "Why is version control important for files?",
          opts: ["It makes files smaller", "It tracks changes so earlier versions can be recovered if something goes wrong", "It prevents others from editing your files", "It automatically backs up files to a printer"],
          correct: 1,
          explanation: "Version control lets you recover earlier drafts and see what changed — critical for collaborative or evolving documents."
        },
      ]
    },
    4: {
      title: "Professional Digital Behaviour and Communication",
      questions: [
        {
          q: "What is digital etiquette?",
          opts: ["Rules for using technology quietly in public", "Respectful and professional behaviour in digital communication", "A company policy about phone use", "Only sending emails during office hours"],
          correct: 1,
          explanation: "Digital etiquette covers how you communicate online — tone, timing, responsiveness, and respect for others."
        },
        {
          q: "What is online reputation?",
          opts: ["Your follower count on social media", "The impression others form of you based on your digital activity and posts", "A credit score calculated from your social media", "A privacy setting on LinkedIn"],
          correct: 1,
          explanation: "Employers, clients, and colleagues often search for you online — your posts and activity shape how you are perceived."
        },
        {
          q: "What is responsible sharing?",
          opts: ["Sharing everything publicly to be transparent", "Thinking carefully before forwarding, posting, or publishing digital content", "Only sharing content created by yourself", "Sharing files only via email"],
          correct: 1,
          explanation: "Before sharing, consider whether content is accurate, private, harmful, or could be misunderstood — once shared, it is hard to take back."
        },
        {
          q: "What is a digital boundary?",
          opts: ["A firewall setting", "A personal rule about when and how you engage with digital communication", "A legal restriction on internet use", "The data limit on your mobile plan"],
          correct: 1,
          explanation: "Digital boundaries protect your wellbeing — for example, not checking work messages after a certain hour."
        },
        {
          q: "Why should you be careful about screenshots and recordings?",
          opts: ["They take up too much storage", "They can expose private conversations or confidential information if shared without consent", "They slow down your device", "Screenshots are always protected by copyright"],
          correct: 1,
          explanation: "Screenshots capture private moments out of context — sharing them without consent can harm relationships and violate privacy."
        },
      ]
    },
  },

  scam: {
    1: {
      title: "Understanding Scams in Southeast Asia",
      questions: [
        {
          q: "What is a scam?",
          opts: ["A legal marketing strategy", "A deceptive scheme designed to trick you into giving away money or personal information", "An aggressive sales technique", "A mistake made by a legitimate business"],
          correct: 1,
          explanation: "Scams are deliberate deceptions — designed specifically to steal money, data, or access from victims."
        },
        {
          q: "What is social engineering in the context of scams?",
          opts: ["Building a social media following", "Manipulating people psychologically to get them to reveal information or take an action", "A type of network hacking tool", "Engineering software for social platforms"],
          correct: 1,
          explanation: "Social engineering exploits trust, fear, urgency, or authority — making victims act against their own interests."
        },
        {
          q: "What is an urgency tactic used by scammers?",
          opts: ["Offering a free gift to slow you down", "Creating artificial time pressure to stop you thinking clearly", "Sending messages slowly over several weeks", "Using polite and patient language"],
          correct: 1,
          explanation: "Scammers create urgency — 'Act now or lose your account!' — to prevent you from pausing to verify."
        },
        {
          q: "Which of the following is a type of phishing?",
          opts: ["A legitimate bank asking you to update your details via their official app", "An email pretending to be your bank asking you to click a link and enter your password", "A text message from a verified retailer about your order", "A phone call from a friend"],
          correct: 1,
          explanation: "Phishing impersonates trusted entities — banks, employers, government — to trick you into handing over credentials."
        },
        {
          q: "What is the Scam Pause Method?",
          opts: ["Waiting 24 hours before filing a scam report", "Stopping to verify before acting — especially when something feels urgent or too good to be true", "Pausing your internet connection when suspicious", "Ignoring all unknown calls for a day"],
          correct: 1,
          explanation: "Pausing breaks the urgency cycle scammers rely on — giving you time to verify the source before acting."
        },
      ]
    },
    2: {
      title: "Spotting Scam Messages, Links, Calls and Websites",
      questions: [
        {
          q: "What is a red flag in a scam message?",
          opts: ["A red envelope icon in your email app", "A warning sign that a message, link, or website may be a scam", "A bold font used in promotional emails", "An email marked as important"],
          correct: 1,
          explanation: "Red flags include urgency, unexpected prizes, suspicious links, grammar errors, and requests for sensitive data."
        },
        {
          q: "What is URL spoofing?",
          opts: ["Shortening a web address with a URL shortener", "Creating a fake web address that looks similar to a legitimate one", "Blocking access to a website", "Encrypting a website link"],
          correct: 1,
          explanation: "Spoofed URLs like 'maybank2u.com.support-login.net' look legitimate but lead to fake sites that steal your login."
        },
        {
          q: "What is caller ID spoofing?",
          opts: ["Blocking your number when calling", "Displaying a fake phone number to make a scam call appear to come from a trusted source", "Recording a phone call without permission", "Using a VoIP service to make calls"],
          correct: 1,
          explanation: "Scammers can fake caller ID to appear as your bank, employer, or government agency — always verify independently."
        },
        {
          q: "What should you do before scanning a QR code from an unknown source?",
          opts: ["Scan it and see what happens", "Verify the source and check the destination URL before proceeding", "Only scan QR codes at night", "Take a screenshot of it first"],
          correct: 1,
          explanation: "Fake QR codes redirect to phishing sites or trigger malware downloads — verify the source before scanning."
        },
        {
          q: "What is a safe verification habit when receiving a suspicious message from a 'bank'?",
          opts: ["Click the link in the message to check if it looks real", "Call the official number on your bank card or their official website to verify", "Reply to the message asking if it is real", "Forward it to a friend to get their opinion"],
          correct: 1,
          explanation: "Never use contact details in a suspicious message — always look up the official number independently and call that."
        },
      ]
    },
    3: {
      title: "Financial, Shopping, Job and Investment Scams",
      questions: [
        {
          q: "What is a marketplace scam?",
          opts: ["A legitimate sale on an e-commerce platform", "A fraudulent listing or buyer/seller interaction designed to steal money or goods", "A flash sale with limited stock", "A refund policy dispute"],
          correct: 1,
          explanation: "Marketplace scams include fake sellers who take payment without delivering, or fake buyers who send counterfeit payment proofs."
        },
        {
          q: "What is a job scam?",
          opts: ["A legitimate job ad with a low salary", "A fake job offer designed to steal money, personal data, or recruit victims into illegal activity", "A job application rejection", "A company that pays below minimum wage"],
          correct: 1,
          explanation: "Job scams promise high pay for easy tasks, ask for upfront fees, or recruit people into scam operations unknowingly."
        },
        {
          q: "What is an investment scam?",
          opts: ["A legitimate stock market investment that performs poorly", "A fraudulent scheme promising unusually high returns to steal money", "A bank's savings account", "A government bond"],
          correct: 1,
          explanation: "Investment scams promise guaranteed, high returns — often using referral networks to recruit more victims before collapsing."
        },
        {
          q: "What is a mule account?",
          opts: ["A savings account for large purchases", "A bank account used (knowingly or unknowingly) to move stolen money on behalf of scammers", "An account for international transfers", "A business account that handles cash"],
          correct: 1,
          explanation: "Scammers recruit mules — often by posing as employers — to transfer stolen funds, making the mule criminally liable."
        },
        {
          q: "What is a loan scam?",
          opts: ["A bank loan with a high interest rate", "A fake loan offer that charges upfront fees and then disappears without providing any loan", "A pay-later option on a shopping app", "A government financial assistance scheme"],
          correct: 1,
          explanation: "Loan scams target people who need money urgently — charging processing fees before vanishing without providing funds."
        },
      ]
    },
    4: {
      title: "AI Scams, Scam Response and Protection Habits",
      questions: [
        {
          q: "What is an AI scam?",
          opts: ["A scam targeting AI companies", "A scam that uses artificial intelligence to generate more convincing fake content, voices, or identities", "An AI tool that accidentally scams users", "A type of computer virus that affects AI software"],
          correct: 1,
          explanation: "AI scams use generated text, voices, images, and video to impersonate trusted people or create convincing fake scenarios."
        },
        {
          q: "What is a deepfake?",
          opts: ["A very convincing lie told in person", "AI-generated video or audio that realistically impersonates a real person", "A fake profile picture", "A digitally edited photo"],
          correct: 1,
          explanation: "Deepfakes use AI to make it appear that a real person said or did something they did not — used in scams to fake authority."
        },
        {
          q: "What is voice cloning?",
          opts: ["Recording someone's voice for a podcast", "Using AI to replicate someone's voice from audio samples to impersonate them in calls or messages", "Auto-transcribing a phone call", "Using a voice changer app for fun"],
          correct: 1,
          explanation: "Voice cloning can replicate a family member's or executive's voice from just seconds of audio — used in urgent fake emergencies."
        },
        {
          q: "What should you do first if you realise you have been scammed?",
          opts: ["Wait to see if the money comes back", "Contact your bank immediately to freeze the transaction or account", "Post about it on social media", "Delete the scammer's messages as evidence"],
          correct: 1,
          explanation: "Time matters — contact your bank immediately. They may be able to freeze or reverse transactions before money is moved."
        },
        {
          q: "Which is a long-term scam protection habit?",
          opts: ["Never using the internet", "Regularly reviewing account activity, using MFA, and verifying unexpected requests before acting", "Only responding to messages from people you know in person", "Changing your phone number every six months"],
          correct: 1,
          explanation: "Long-term protection is about consistent habits — monitoring accounts, using MFA, and pausing before acting on urgent requests."
        },
      ]
    },
  },
};
